'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BILL1
    Public Property BID As Integer
    Public Property BDATE As Nullable(Of Date)
    Public Property BNO As String
    Public Property CUST As String
    Public Property SNAME As String
    Public Property GTOT As Nullable(Of Decimal)
    Public Property TOTAL As Nullable(Of Decimal)
    Public Property PAYMENT As Nullable(Of Decimal)
    Public Property SECTOR As String
    Public Property ADDRESS As String
    Public Property ROUND As Nullable(Of Decimal)
    Public Property NTOT As Nullable(Of Decimal)
    Public Property TVAL As Nullable(Of Decimal)
    Public Property USER1 As String
    Public Property MODE As String
    Public Property VNO As String
    Public Property CBILL As Nullable(Of Decimal)
    Public Property BAPAY As Nullable(Of Decimal)
    Public Property BST As String
    Public Property SSTA As String
    Public Property DPCODE As String
    Public Property LMODI As String
    Public Property BID1 As String
    Public Property AEDT As String
    Public Property BAMT As Nullable(Of Decimal)

End Class
