'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations
Imports System.Web.DynamicData

Partial Public Class MAINPOPU
    Public Property RID As Integer
    Public Property RID1 As String
    Public Property SID As String
    Public Property CNAME As String
    Public Property SNAME As String
    Public Property ENS As String
    Public Property ALSN As String
    Public Property RAT_PH As String
    Public Property PHASE As String
    Public Property MODEL As String
    Public Property BSN As String
    Public Property CPN As String
    Public Property PHNO As String
    Public Property ADDR As String
    <DisplayFormat(ApplyFormatInEditMode:=True, DataFormatString:="{0:dd-MMMM-yyyy}")>
    Public Property DOC As Nullable(Of Date)
    Public Property SPIN As String
    Public Property AMC As String
    Public Property CHMR As String
    Public Property CHMD As Nullable(Of Date)
    Public Property lhmr As String
    Public Property lsd As Nullable(Of Date)
    Public Property nsd As Nullable(Of Date)
    Public Property ahm As String
    Public Property DGNO As String
    Public Property ACTION As String
    Public Property DIST As String
    Public Property STATE As String
    Public Property AMAKE As String
    Public Property WARR As String
    Public Property OEA As String
    Public Property SSTA As String
    Public Property hmage As String
    Public Property DPCODE As String
    Public Property lmodi As String
    Public Property AEDT As String
    Public Property llop As String
    Public Property solenoid As String
    Public Property chalt As String
    Public Property starter As String
    Public Property cntype As String
    Public Property cnmake As String
    Public Property sauto As String
    Public Property FRAME As String
    Public Property DSTA As String

End Class
