'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PURCHSE
    Public Property BILLID As Integer
    Public Property BID As String
    Public Property BILL_NO As String
    Public Property BDATE As Nullable(Of Date)
    Public Property DNAME As String
    Public Property CUST As String
    Public Property PART_NO As String
    Public Property PARTI As String
    Public Property QTY As String
    Public Property MRP As String
    Public Property SPRICE As String
    Public Property TOTAL As String
    Public Property TAX As String
    Public Property TVAL As String
    Public Property STOT As String
    Public Property CMP As String
    Public Property UNIT As String
    Public Property USER1 As String
    Public Property MODE As String
    Public Property SSTA As String
    Public Property DPCODE As String
    Public Property LMODI As String
    Public Property AEDT As String
    Public Property BAMT As Nullable(Of Decimal)

End Class
