'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SHEET1
    Public Property RID As Integer
    Public Property PART_NO As String
    Public Property PARTI As String
    Public Property MRP As String
    Public Property GROP As String
    Public Property CATE As String
    Public Property DPCODE As String
    Public Property lmodi As String
    Public Property TRATE As String
    Public Property rid1 As String
    Public Property unit As String
    Public Property AEDT As String

End Class
