'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class TABLE1
    Public Property RID1 As Integer
    Public Property RID As String
    Public Property TYPE As String
    Public Property PART_NO As String
    Public Property PARTI As String
    Public Property MRP As String
    Public Property QTY As String
    Public Property TOTAL As String
    Public Property RACKNO As String
    Public Property TAX As String
    Public Property TVAL As String
    Public Property STOTAL As String
    Public Property PPRICE As String
    Public Property UNIT As String
    Public Property SPRICE As String
    Public Property SSTA As String
    Public Property EOR As String
    Public Property DPCODE As String
    Public Property lmodi As String
    Public Property grop As String
    Public Property AEDT As String
    Public Property USER1 As String

End Class
