'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class user1
    Public Property CID As Integer
    <Required(ErrorMessage:="Please Provide Username", AllowEmptyStrings:=False)>
    Public Property uid As String
    <Required(ErrorMessage:="Please provide password", AllowEmptyStrings:=False)> _
    <DataType(System.ComponentModel.DataAnnotations.DataType.Password)>
    Public Property pass As String
    Public Property fname As String
    Public Property lname As String

End Class
